[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
name = "squill"
version = "0.0.0"
description = "Tool for managing database revisions"
license.text = "BSD-3-Clause"

[tool.mypy]
files = ["src", "tests"]

[tool.pytest.ini_options]
testpaths = ["tests"]
